/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegodeoca;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Eli
 */
public class JuegoForm extends javax.swing.JInternalFrame {

    ArrayList<Tematica> listaTematicas;
    ArrayList<Pregunta> listaPreguntas;
    ArrayList<Comodin> listaComodines;
    ArrayList<Premio> listaPremios;
    ArrayList<Castigo> listaCastigos;

    private LogicaJuegoOca lj;
    private Dado d;
    private Pregunta[] preguntas;
    private String[] temas;

    public JuegoForm() {
        initComponents();

        listaTematicas = new ArrayList<Tematica>();
        listaPreguntas = new ArrayList<Pregunta>();
        listaCastigos = new ArrayList<Castigo>();
        listaPremios = new ArrayList<Premio>();
        listaComodines = new ArrayList<Comodin>();

        temas = new String[6];
        //temas = {"Biologia", "Historia", "Matematicas", "comodin", "premio", "castigo"};
        // Estos si se cambian , si pueden cambiar por los temas de las preguntas
        temas[0] = "Biologia";
        temas[1] = "Historia";
        temas[2] = "Matematicas";

        // No Modificar pibe
        temas[3] = "comodin";
        temas[4] = "premio";
        temas[5] = "castigo";
        d = new Dado(temas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tablero = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn19 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();
        btn25 = new javax.swing.JButton();
        btn26 = new javax.swing.JButton();
        btn27 = new javax.swing.JButton();
        btn28 = new javax.swing.JButton();
        btn29 = new javax.swing.JButton();
        btn30 = new javax.swing.JButton();
        btn31 = new javax.swing.JButton();
        btn32 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        btn34 = new javax.swing.JButton();
        btn35 = new javax.swing.JButton();
        btn36 = new javax.swing.JButton();
        btn37 = new javax.swing.JButton();
        btn38 = new javax.swing.JButton();
        btn39 = new javax.swing.JButton();
        btn40 = new javax.swing.JButton();
        btn41 = new javax.swing.JButton();
        btn42 = new javax.swing.JButton();
        btn43 = new javax.swing.JButton();
        btn44 = new javax.swing.JButton();
        btn45 = new javax.swing.JButton();
        btn46 = new javax.swing.JButton();
        btn47 = new javax.swing.JButton();
        btn48 = new javax.swing.JButton();
        btn49 = new javax.swing.JButton();
        btn50 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        etiNombreJugador = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        etiJugadorPuntero = new javax.swing.JLabel();
        etiDado = new javax.swing.JLabel();
        etiAvanza = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Juego de la Oca");

        tablero.setBorder(javax.swing.BorderFactory.createTitledBorder("Tablero"));

        btn1.setText("1");

        btn2.setText("2");

        btn3.setText("3");

        btn4.setText("4");

        btn5.setText("5");

        btn6.setText("6");

        btn7.setText("7");

        btn8.setText("8");

        btn10.setText("10");

        btn9.setText("9");

        btn11.setText("11");

        btn12.setText("12");

        btn13.setText("13");

        btn14.setText("14");

        btn15.setText("15");

        btn16.setText("16");

        btn17.setText("17");

        btn18.setText("18");

        btn20.setText("20");

        btn19.setText("19");

        btn21.setText("21");

        btn22.setText("22");

        btn23.setText("23");

        btn24.setText("24");

        btn25.setText("25");

        btn26.setText("26");

        btn27.setText("27");
        btn27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn27ActionPerformed(evt);
            }
        });

        btn28.setText("28");

        btn29.setText("29");

        btn30.setText("30");

        btn31.setText("31");

        btn32.setText("32");

        btn33.setText("33");

        btn34.setText("34");

        btn35.setText("35");

        btn36.setText("36");

        btn37.setText("37");

        btn38.setText("38");

        btn39.setText("39");

        btn40.setText("40");

        btn41.setText("41");

        btn42.setText("42");

        btn43.setText("43");

        btn44.setText("44");

        btn45.setText("45");

        btn46.setText("46");

        btn47.setText("47");

        btn48.setText("48");

        btn49.setText("49");

        btn50.setText("50");

        javax.swing.GroupLayout tableroLayout = new javax.swing.GroupLayout(tablero);
        tablero.setLayout(tableroLayout);
        tableroLayout.setHorizontalGroup(
            tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableroLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableroLayout.createSequentialGroup()
                        .addComponent(btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableroLayout.createSequentialGroup()
                        .addComponent(btn11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableroLayout.createSequentialGroup()
                        .addComponent(btn21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableroLayout.createSequentialGroup()
                        .addComponent(btn31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableroLayout.createSequentialGroup()
                        .addComponent(btn41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn50)))
                .addContainerGap())
        );
        tableroLayout.setVerticalGroup(
            tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1)
                    .addComponent(btn2)
                    .addComponent(btn3)
                    .addComponent(btn4)
                    .addComponent(btn5)
                    .addComponent(btn6)
                    .addComponent(btn7)
                    .addComponent(btn8)
                    .addComponent(btn9)
                    .addComponent(btn10))
                .addGap(18, 18, 18)
                .addGroup(tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn11)
                    .addComponent(btn12)
                    .addComponent(btn13)
                    .addComponent(btn14)
                    .addComponent(btn15)
                    .addComponent(btn16)
                    .addComponent(btn17)
                    .addComponent(btn18)
                    .addComponent(btn19)
                    .addComponent(btn20))
                .addGap(26, 26, 26)
                .addGroup(tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn21)
                    .addComponent(btn22)
                    .addComponent(btn23)
                    .addComponent(btn24)
                    .addComponent(btn25)
                    .addComponent(btn26)
                    .addComponent(btn27)
                    .addComponent(btn28)
                    .addComponent(btn29)
                    .addComponent(btn30))
                .addGap(27, 27, 27)
                .addGroup(tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn31)
                    .addComponent(btn32)
                    .addComponent(btn33)
                    .addComponent(btn34)
                    .addComponent(btn35)
                    .addComponent(btn36)
                    .addComponent(btn37)
                    .addComponent(btn38)
                    .addComponent(btn39)
                    .addComponent(btn40))
                .addGap(18, 18, 18)
                .addGroup(tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn41)
                    .addComponent(btn42)
                    .addComponent(btn43)
                    .addComponent(btn44)
                    .addComponent(btn45)
                    .addComponent(btn46)
                    .addComponent(btn47)
                    .addComponent(btn48)
                    .addComponent(btn49)
                    .addComponent(btn50))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Turno:");

        jLabel4.setText("Jugador Puntero:");

        etiDado.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        etiDado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(129, 129, 129))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(etiJugadorPuntero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(etiNombreJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 46, Short.MAX_VALUE)
                                        .addComponent(etiAvanza, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(etiDado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIniciar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(etiJugadorPuntero, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(etiNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(etiDado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(etiAvanza, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIniciar))
                    .addComponent(tablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed

        System.out.println(CargaDatos("castigo"));
        System.out.println(CargaDatos("premio"));
        System.out.println(CargaDatos("comodin"));
        System.out.println(CargaDatos("pregunta"));

        Comodin[] Array_comodin = new Comodin[listaComodines.size()];
        Array_comodin = listaComodines.toArray(Array_comodin);
        Premio[] Array_premio = new Premio[listaPremios.size()];
        Array_premio = listaPremios.toArray(Array_premio);
        Castigo[] Array_castigo = new Castigo[listaCastigos.size()];
        Array_castigo = listaCastigos.toArray(Array_castigo);
        Pregunta[] Array_preguntas = new Pregunta[listaPreguntas.size()];
        Array_preguntas = listaPreguntas.toArray(Array_preguntas);

        
        String msjColor ="\n1)Negro\n2)Azul\n3)Rojo\n4)Amarillo\n5)Rosa\n6)Naranja\n7)Gris\n8)Blanco\n9)Verde\n10)Morado";
        int tamanio = Integer.parseInt(JOptionPane.showInputDialog("Ingrese numero de Jugadores"));
        Jugador[] jugadores = new Jugador[tamanio];
        int j = 1;
        for (int i = 0; i < tamanio; i++) {
            
            String nombre = JOptionPane.showInputDialog("Ingrese Nombre jugador # " + j);
            String selColor = JOptionPane.showInputDialog("Seleccione Color para " + nombre +msjColor);
            jugadores[i] = new Jugador(nombre, establece_color(selColor));
            j++;
        }
        lj = new LogicaJuegoOca(jugadores);
        String ganador = lj.Game(temas, Array_preguntas, Array_comodin, Array_premio, Array_castigo, d).getNombre();
        JOptionPane.showMessageDialog(rootPane, "Jugador Ganador:" + ganador);
    }//GEN-LAST:event_btnIniciarActionPerformed

    public Color establece_color(String selColor) {
        Color color = null;
        switch (selColor) {
            case "1":
                color = Color.BLACK;
                break;
            case "2":
                color = Color.BLUE;
                break;
            case "3":
                color = Color.RED;
                break;
            case "4":
                color = Color.YELLOW;
                break;
            case "5":
                color = Color.PINK;
                break;
            case "6":
                color = Color.ORANGE;
                break;
            case "7":
                color = Color.GRAY;
                break;
            case "8":
                color = Color.white;
                break;
            case "9":
                color = Color.green;
                break;
            case "10":
                color = Color.MAGENTA;
                break;

        }
        return color;
    }
    private void btn27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn27ActionPerformed

    private String eligeRuta(String tipo) {
        String ruta = new String();
        switch (tipo) {
            case "castigo":
                ruta += "castigos.txt";
                break;
            case "premio":
                ruta += "premios.txt";
                break;
            case "comodin":
                ruta += "comodin.txt";
                break;
            case "pregunta":
                ruta += "pregunta.txt";
                break;
            case "tematica":
                ruta += "tematica.txt";
                break;
        }
        return ruta;
    }

    private String CargaDatos(String tipo) {

        String ruta = eligeRuta(tipo);
        System.out.println("Ruta encontrada: " + ruta);
        String falsas[];
        falsas = new String[3];
        try {
            File archivo1 = new File(ruta);
            FileReader fr = new FileReader(archivo1);
            BufferedReader br = new BufferedReader(fr);
            String linea = br.readLine();
            // Campos [0] = clave,Campos[1]=texto,Campos[2]=valor pregunta,Campos[3] = Tematica ,Campos[4] = Respuesta Falsas
            while (linea != null) {
                String[] campos = linea.split("@");
                if (!ruta.equalsIgnoreCase("pregunta.txt")) {
                    AgregaDatos(campos, ruta, "");
                } else {
                    String res_falsas = campos[3];
                    AgregaDatos(campos, ruta, res_falsas);
                }
                linea = br.readLine();
            }

            fr.close();
            return "Datos " + tipo + " Cargados";
        } catch (Exception e) {
            System.out.println(e);
            return "Error " + tipo + " NO Cargados";
        }

    }

    private void AgregaDatos(String[] valores, String ruta, String res_falsas) {
        System.out.println(Arrays.toString(valores));
        switch (ruta) {
            case "tematica.txt": {
                listaTematicas.add(new Tematica(valores[0], valores[1]));
            }
            break;
            case "castigos.txt": {
                listaCastigos.add(new Castigo(valores[0], valores[1]));
            }
            break;
            case "premios.txt": {
                listaPremios.add(new Premio(valores[0], valores[1]));
            }
            break;
            case "comodin.txt": {
                listaComodines.add(new Comodin(valores[0], valores[1]));
            }
            break;
            case "pregunta.txt": {
                //(String pregunta, String respuesta_correcta, String tematica,String[] respuestas_incorrectas)
                String[] falsas = res_falsas.split("¬");
                listaPreguntas.add(new Pregunta(valores[0], valores[1], valores[2], falsas));
            }
            break;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn1;
    public static javax.swing.JButton btn10;
    public static javax.swing.JButton btn11;
    public static javax.swing.JButton btn12;
    public static javax.swing.JButton btn13;
    public static javax.swing.JButton btn14;
    public static javax.swing.JButton btn15;
    public static javax.swing.JButton btn16;
    public static javax.swing.JButton btn17;
    public static javax.swing.JButton btn18;
    public static javax.swing.JButton btn19;
    public static javax.swing.JButton btn2;
    public static javax.swing.JButton btn20;
    public static javax.swing.JButton btn21;
    public static javax.swing.JButton btn22;
    public static javax.swing.JButton btn23;
    public static javax.swing.JButton btn24;
    public static javax.swing.JButton btn25;
    public static javax.swing.JButton btn26;
    public static javax.swing.JButton btn27;
    public static javax.swing.JButton btn28;
    public static javax.swing.JButton btn29;
    public static javax.swing.JButton btn3;
    public static javax.swing.JButton btn30;
    public static javax.swing.JButton btn31;
    public static javax.swing.JButton btn32;
    public static javax.swing.JButton btn33;
    public static javax.swing.JButton btn34;
    public static javax.swing.JButton btn35;
    public static javax.swing.JButton btn36;
    public static javax.swing.JButton btn37;
    public static javax.swing.JButton btn38;
    public static javax.swing.JButton btn39;
    public static javax.swing.JButton btn4;
    public static javax.swing.JButton btn40;
    public static javax.swing.JButton btn41;
    public static javax.swing.JButton btn42;
    public static javax.swing.JButton btn43;
    public static javax.swing.JButton btn44;
    public static javax.swing.JButton btn45;
    public static javax.swing.JButton btn46;
    public static javax.swing.JButton btn47;
    public static javax.swing.JButton btn48;
    public static javax.swing.JButton btn49;
    public static javax.swing.JButton btn5;
    public static javax.swing.JButton btn50;
    public static javax.swing.JButton btn6;
    public static javax.swing.JButton btn7;
    public static javax.swing.JButton btn8;
    public static javax.swing.JButton btn9;
    private javax.swing.JButton btnIniciar;
    public static javax.swing.JLabel etiAvanza;
    public static javax.swing.JLabel etiDado;
    public static javax.swing.JLabel etiJugadorPuntero;
    public static javax.swing.JLabel etiNombreJugador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel tablero;
    // End of variables declaration//GEN-END:variables
}
