/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegodeoca;

import javax.swing.JOptionPane;

/**
 *
 * @author Eli
 */
public class PrincipalJuegoOca extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalJuegoOca
     */
    public PrincipalJuegoOca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        menuJuego = new javax.swing.JMenuItem();
        MenuConfig = new javax.swing.JMenu();
        menuConfigGlo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego de la OCA");
        setResizable(false);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Inicio");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        menuJuego.setMnemonic('o');
        menuJuego.setText("Juego");
        menuJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuJuegoActionPerformed(evt);
            }
        });
        fileMenu.add(menuJuego);

        menuBar.add(fileMenu);

        MenuConfig.setMnemonic('e');
        MenuConfig.setText("Configuraciones");

        menuConfigGlo.setText("Configuraciones Globales");
        menuConfigGlo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConfigGloActionPerformed(evt);
            }
        });
        MenuConfig.add(menuConfigGlo);

        menuBar.add(MenuConfig);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuConfigGloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConfigGloActionPerformed
        String clave = JOptionPane.showInputDialog(escritorio, "Ingrese contraseña", "Login", HEIGHT);

        if (clave.equalsIgnoreCase("panda")) {
            FrmConfiguracion frmconfig = new FrmConfiguracion();
            escritorio.add(frmconfig);
            frmconfig.toFront();
            frmconfig.setLocation(0, 0);
            frmconfig.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(escritorio, "USTED NO ES UN PANDA","Error Fatal", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuConfigGloActionPerformed

    private void menuJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuJuegoActionPerformed
              JuegoForm frmJuego = new JuegoForm();
            escritorio.add(frmJuego);
            frmJuego.toFront();
            frmJuego.setLocation(0, 0);
            frmJuego.setVisible(true);
    }//GEN-LAST:event_menuJuegoActionPerformed

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJuegoOca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJuegoOca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJuegoOca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJuegoOca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJuegoOca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuConfig;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuConfigGlo;
    private javax.swing.JMenuItem menuJuego;
    // End of variables declaration//GEN-END:variables

}
